---
build_dir: /tmp/build
user: azureuser

hashicorp_consul_url: "https://releases.hashicorp.com/consul/"
hashicorp_consul_version: "1.13.6"
#"/1.13.6/consul_1.13.6_linux_amd64.zip"
hashicorp_consul_checksum: "sha256:7d671f86263021daa91f581fe720e02a17aabb9c226e97b5ce1d55b09f888711"

hashicorp_vault_url: "https://releases.hashicorp.com/vault/"
hashicorp_vault_version: "1.12.3"
#"/1.12.3/vault_1.12.3_linux_amd64.zip"
hashicorp_vault_checksum: "sha256:f4825bad06e77687b407eff7423acb9238adfd545d7345f2a0bb9e81b0c4b1eb"

binary_version: linux_amd64

consul_binary: "consul_{{hashicorp_consul_version }}_{{ binary_version }}"
vault_binary: "vault_{{hashicorp_vault_version }}_{{ binary_version }}"

vault_user: "vault" #The account that will be created and used to run Vault
consul_user: "consul" #The account that will be created and used to run Consul