---
# - hosts: consul:vault
#   gather_facts: no
#   remote_user: "{{user}}"
#   become: no
#   tasks:

#     - name: Enable consul layer gossip encryption
#       include_role:
#         name: consul-enable-encryption

# - hosts: consul:vault
#   gather_facts: no
#   remote_user: "{{user}}"
#   become: yes
#   tasks:

#     - name: Restart Consul service
#       ansible.builtin.service:
#         name: "{{ consul_user }}"
#         state: restarted
#         daemon_reload: true

    

    # - name: Initialise Vault
    #   include_role:
    #     name: vault-init

    # - name: Unseal Vault
    #   include_role:
    #     name: vault-unseal

    # - name: Enable Vault audit logs
    #   include_role:
    #     name: vault-enable-audit
    
    # - name: Bootstrap AppRole
    #   include_role:
    #     name: bootstrap-approle

    # - name: Create CAs
    #   include_role:
    #     name: create-issuing-ca

    # - name: Enable TLS
    #   include_role:
    #     name: enable-tls