---
- hosts: ansible
  gather_facts: no
  remote_user: "{{user}}"
  become: no
  tasks:   

    - name: Enable vault service #Due to previous build actions the primary Vault server returns 500 for the next step so needs restarted first
      become: true
      ansible.builtin.service:
        name: "{{ vault_user }}"
        state: restarted
        daemon_reload: true

    - name: Initialise Vault
      include_role:
        name: vault-init

    - name: Unseal Vault
      include_role:
        name: vault-unseal

    - name: Enable Vault audit logs
      include_role:
        name: vault-enable-audit
    
    - name: Bootstrap Terraform JWT auth
      include_role:
        name: bootstrap-tf-jwt

    - name: Create CAs
      include_role:
        name: create-issuing-ca


