- hosts: ansible
  gather_facts: no
  remote_user: "{{user}}"
  become: yes
  tasks:   
    - name: Initialise Vault
      include_role:
        name: vault-init
    - name: Unseal Vault
      include_role:
        name: vault-unseal
    - name: Enable Vault audit logs
      include_role:
        name: vault-enable-audit
    - name: Bootstrap Terraform JWT auth
      include_role:
        name: bootstrap-tf-jwt