---

- hosts: ansible
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  pre_tasks:
    - name: Read Vault root token from disk
      slurp:
        src: "{{ vault_root_token_file }}" #TODO - THIS FILE IS NOT ON THE CONSUL HOSTS HENCE ERROR
      register: slurp_contents
    - name: Extract root token
      set_fact: 
        vault_token_t: "{{ slurp_contents['content'] | b64decode }}"
    - name: Print Vault Token Found
      debug:
        msg: "Vault Token Found: {{ vault_token_t }}."

- hosts: consul
  gather_facts: yes
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: Create Consul server TLS certificates
      include_role:
        name: consul-create-tls-certs
      vars:
        vault_hostname: "{{ groups['ansible'][0] }}"
        cert_file: "/etc/{{ consul_user }}.d/consul_cert.pem"
        key_file: "/etc/{{ consul_user }}.d/consul_key.pem"
        ca_file: "/etc/{{ consul_user }}.d/ca_cert.pem"
        alt_names: "{{ inventory_hostname }},server.dc1.consul" #required alt_name format for Consul servers
        cname: "{{ inventory_hostname }}"
        vault_token: hostvars['ansible']['vault_token_t']
        
- hosts: vault
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: Create Consul client TLS certificates
      include_role:
        name: consul-create-tls-certs
      vars:
        vault_hostname: "{{ groups['ansible'][0] }}"
        cert_file: "/etc/{{ consul_user }}.d/consul_cert.pem"
        key_file: "/etc/{{ consul_user }}.d/consul_key.pem"
        ca_file: "/etc/{{ consul_user }}.d/ca_cert.pem" #required alt_name format for Consul clients
        alt_names: "{{ inventory_hostname }}-consul"
        cname: "{{ inventory_hostname }}"

    - name: Create Vault server TLS certificates
      include_role:
        name: vault-create-tls-certs
      vars:
        vault_hostname: "{{ groups['ansible'][0] }}"
        cert_file: "/etc/{{ vault_user }}.d/vault_cert.pem"
        key_file: "/etc/{{ vault_user }}.d/vault_key.pem"
        ca_file: "/etc/{{ vault_user }}.d/ca_cert.pem"
        alt_names: "{{ inventory_hostname }}"
        cname: "{{ inventory_hostname }}"

- hosts: consul:vault
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: Update consul server and client TLS configuration
      include_role:
        name: consul-enable-tls
      vars:
        config_file: "/etc/{{ consul_user }}.d/consul.hcl"
       
- hosts: vault
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: Update the vault TLS configuration
      include_role:
        name: vault-enable-tls
      vars:
        config_file: "/etc/{{ vault_user }}.d/vault.hcl"
    
    - name: Unseal Vault
      include_role:
        name: vault-unseal
