---
- hosts: ansible
  gather_facts: no
  remote_user: "{{ user }}"
  become: no

  tasks:
    - name: Fetch the Hashicorp Vault and Consul binaries to use for the install, unzip and copy to servers
      include_role:
        name: fetch-binaries

    - name: Install zip  (state=present is optional)
      become: true
      ansible.builtin.apt:
        name: zip
        state: present

    - name: Unarchive Consul binary
      ansible.builtin.unarchive:
        src: "{{ build_dir }}/{{ consul_binary }}.zip"
        dest: "{{ build_dir }}" #/usr/local/bin
        remote_src: yes
        list_files: yes
      register: unpacked_consul

    - name: Unarchive Vault binary
      ansible.builtin.unarchive:
        src: "{{ build_dir }}/{{ vault_binary }}.zip"
        dest: "{{ build_dir }}" #/usr/local/bin
        remote_src: yes
        list_files: yes
      register: unpacked_vault
     
- hosts: consul:vault
  tasks:
    - name: Create a directory /tmp/build
      file:
        path: "{{ build_dir }}"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ user }}"
    - name: Copy the Consul binary to all servers
      ansible.builtin.copy:
        src: "{{ build_dir }}/consul"
        dest: "{{ build_dir }}/{{ consul_binary }}"
        mode: 0751
        user: "{{ consul_user }}" #user must have been created first
        group: "root"

- hosts: vault
  tasks:
    - name: Copy the Vault binary to the Vault servers
      ansible.builtin.copy:
        src: "{{ build_dir }}/vault" #{{ unpacked_vault.files[0] }}" #local location of binary tried grabbing file list however register doesnt work between plays
        dest: "{{ build_dir }}/{{ vault_binary }}" #store in same location with same name on the remote
        mode: 0751
        user: "{{ vault_user }}" #user must have been created first
        group: "root"
        
    # - name: Unarchive a file that is already on the remote machine
    #   ansible.builtin.unarchive:
    #     src: "{{ build_dir }}/{{ vault_binary }}.zip"
    #     dest: "{{ build_dir }}" #/usr/local/bin
    #     remote_src: yes