---
- hosts: all
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  vars:
    - new_user: "{{ consul_user }}"
    - new_group: "{{ consul_user }}"
    - base_user: "{{ user }}"
  tasks:
    - name: Create new user and group on Consul servers and software folders
      include_role:
        name: init-servers


- hosts: vault
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  vars:
    - new_user: "{{ vault_user }}"
    - new_group: "{{ vault_user }}"
    - base_user: "{{ user }}"
  tasks:
    - name: Create new user and group on Vault servers and software folders
      include_role:
        name: init-servers