---
- hosts: ansible
  gather_facts: no
  remote_user: "{{user}}"
  become: true
  tasks:   

    - name: Restart vault service #Due to previous build actions the primary Vault server returns 500 for the next step so needs restarted first
      become: true
      ansible.builtin.service:
        name: "{{ vault_user }}"
        state: restarted
        daemon_reload: true

    - name: Unseal Vault
      include_role:
        name: vault-unseal

    # TODO - the below doesnt work. Timeout trying to retrieve public IP address of host.
    - name: Create Vault server TLS certificates #public IP address has probably changed so re-issue certs
      include_role:
        name: vault-create-tls-certs
      vars:
        vault_hostname: "{{ groups['ansible'][0] }}"
        cert_file: "/etc/{{ vault_user }}.d/vault_cert.pem"
        key_file: "/etc/{{ vault_user }}.d/vault_key.pem"
        ca_file: "/etc/{{ vault_user }}.d/ca_cert.pem"
        alt_names: "{{ inventory_hostname }}"
        cname: "{{ inventory_hostname }}"

- hosts: vault
  gather_facts: no
  remote_user: "{{user}}"
  become: no
  tasks:

    - name: Restart vault service #Now restart to detect certificate changes
      become: true
      ansible.builtin.service:
        name: "{{ vault_user }}"
        state: restarted
        daemon_reload: true

    - name: Unseal Vault #Other Vault needs need unsealed
      include_role:
        name: vault-unseal