---
## ansible-playbook -e "@vault/passwd.yml" init-unseal-vault.yml --check
#NOTE: force_init not implemented. Would require additional functionality to stop vault & consul clients, issue consul delete command, restart

# The default status codes are:
#   200 if initialized, unsealed, and active
#   429 if unsealed and standby
#   472 if data recovery mode replication secondary and active
#   501 if not initialized
#   503 if sealed
- name: Check if vault is initialised
  uri:
    url: "{{ vault_tls_disable | ternary('http', 'https') }}://{{ inventory_hostname }}:{{ vault_port }}/v1/sys/health"
    validate_certs: "{{ tls_skip_verify | ternary('false', 'true') }}"
    status_code: 200,429,472,501,503
  register: vault_health_response
  delay: 5 #every 5 seconds
  retries: 12 #12*5 = 1 minutes (During the build there can be a delay to startup all services so keep retrying this check)
  until: ('status' in vault_health_response) and (vault_health_response.status != -1)


- block:
  - name: Initialize vault
    uri:
      url: "{{ vault_tls_disable | ternary('http', 'https') }}://{{ inventory_hostname }}:{{ vault_port }}/v1/sys/init"
      body:
        secret_shares: "{{ vault_secret_shares }}"
        secret_threshold: "{{ vault_secret_threshold }}"
      body_format: json
      method: PUT
      validate_certs: "{{ tls_skip_verify | ternary('false', 'true') }}"
    register: init_vault_response

  - name: Save vault root token and keys
    set_fact:
      vault_root_token: "{{ init_vault_response.json.root_token }}"
      vault_keys: "{{ init_vault_response.json.keys_base64 }}"

  - name: Display vault root token
    debug:
      msg: "Root Token: {{ vault_root_token }}"
    when: display_init_response | bool

  - name: Display vault keys # separate for pretty printing
    debug:
      msg: "Vault keys: {{ vault_keys }}"
    when: display_init_response | bool

  - name: Write unseal keys to file
    copy:
      dest: "{{ vault_unseal_keys_file }}"
      content: "{{ vault_keys }}"
    delegate_to: localhost
  
  - name: Write root token to file
    copy:
      content: "{{ vault_root_token }}"
      dest: "{{ vault_root_token_file }}"
    delegate_to: localhost

  no_log: false
  run_once: true
  when:
    - vault_health_response.status == 501 or vault_force_reinit