---

vault_token: "{{ lookup('file', '{{ vault_root_token_file }}', errors='ignore') }}" #if already initialised root token may exist in file so read it in so that audit check can be done

issuing_ca_name: vaultca-issuer
issuing_ca_file: "/home/{{ vault_user }}/certs/issuing_ca.cer"
ca_lifetime: 315360000 #10 years (in seconds)
leaf_cert_lifetime: 94607990 #3 years in seconds
issuing_ca_role: leaf_certs