---

- name: Set the consul config to use TLS
  lineinfile:
    dest: "{{ config_file }}"
    regexp: "{{ config_text.regexp }}"
    line: "{{ config_text.line }}"
    backrefs: true
  loop:
    - { regexp: '^#ca_file\s(.*?)$', line: 'ca_file  \1' }
    - { regexp: '^#cert_file\s(.*?)$', line: 'cert_file  \1' }
    - { regexp: '^#key_file\s(.*?)$', line: 'key_file  \1' }
    - { regexp: '^#verify_incoming\s(.*?)$', line: 'verify_incoming  \1' }
    - { regexp: '^#verify_outgoing\s(.*?)$', line: 'verify_outgoing  \1' }
    - { regexp: '^#verify_server_hostname\s(.*?)$', line: 'verify_server_hostname  \1' }
  loop_control:
    loop_var: config_text

- name: Restart Consul service
  ansible.builtin.service:
    name: "{{ consul_user }}"
    state: restarted
    daemon_reload: true